# Generated by Django 5.1.3 on 2024-12-05 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "candidates_team",
            },
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("years_of_experience", models.IntegerField()),
                ("skillset", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("Interview Scheduled", "Interview Scheduled"),
                            ("Selected", "Selected"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Open",
                        max_length=20,
                    ),
                ),
                ("cv", models.FileField(upload_to="cvs/")),
                (
                    "rejected_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rejected_candidates",
                        to="candidates.team",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="candidates.team",
                    ),
                ),
            ],
            options={
                "db_table": "candidates_candidate",
            },
        ),
    ]
