# Generated by Django 5.1.3 on 2025-01-16 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("years_of_experience", models.IntegerField()),
                ("skillset", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("Interview Scheduled", "Interview Scheduled"),
                            ("Selected", "Selected"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Open",
                        max_length=20,
                    ),
                ),
                ("cv", models.FileField(upload_to="cvs/")),
                ("scheduled_time", models.DateTimeField(blank=True, null=True)),
                ("notice_period", models.IntegerField(blank=True, null=True)),
                ("current_company", models.CharField(blank=True, max_length=200)),
                ("qualification", models.CharField(blank=True, max_length=200)),
                ("current_location", models.CharField(blank=True, max_length=200)),
                (
                    "vendor",
                    models.CharField(blank=True, default="OLVT", max_length=200),
                ),
                ("file_url", models.URLField(blank=True, max_length=1024, null=True)),
            ],
            options={
                "db_table": "candidates_candidate",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[("admin", "Admin"), ("candidate", "Candidate")],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "candidates_team",
            },
        ),
        migrations.CreateModel(
            name="RejectionComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rejection_comments",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidates.team",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="candidate",
            name="rejected_by",
            field=models.ManyToManyField(
                blank=True, related_name="rejected_candidates", to="candidates.team"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="candidates.team",
            ),
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="candidates.candidate",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_time_slots",
                        to="candidates.team",
                    ),
                ),
            ],
            options={
                "db_table": "candidates_timeslot",
                "unique_together": {("candidate", "date", "time")},
            },
        ),
    ]
