# Generated by Django 5.1.3 on 2024-12-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="scheduled_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
