# Generated by Django 5.1.3 on 2025-01-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0002_alter_candidate_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="email",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
