# Generated by Django 5.1.3 on 2025-01-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0003_candidate_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
