# Generated by Django 5.1.3 on 2025-01-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0005_alter_candidate_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
