# Generated by Django 5.1.3 on 2025-01-31 08:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0006_alter_candidate_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="HrTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[("hr", "Hr"), ("interviewer", "Interviewer")],
                        max_length=11,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "hr_team",
            },
        ),
        migrations.CreateModel(
            name="Interviewer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("years_of_experience", models.IntegerField()),
                ("skillset", models.CharField(max_length=200)),
                ("email", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "interviewer_details",
            },
        ),
        migrations.CreateModel(
            name="InterviewerTimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_time_slots",
                        to="candidates.hrteam",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviewer_time_slots",
                        to="candidates.interviewer",
                    ),
                ),
            ],
            options={
                "db_table": "interviewer_timeslot",
                "unique_together": {("interviewer", "date", "time")},
            },
        ),
    ]
